{
  "Id": "1414515",
  "IdGerrit": "149923",
  "Files": "nova/servicegroup/api.py,nova/servicegroup/drivers/base.py,nova/servicegroup/drivers/db.py,nova/servicegroup/drivers/zk.py",
  "CommitParent": "5a9d7abb98ffc9af8380fdf6429915f80bb19656",
  "CommitPrevious": "64e167eb\nedec3e1b\nd4cf1156\nb055e168\n8c53d87a\n8880aadb\ne61bf701\nc7718b2d",
  "Responsible": "Atleastone",
  "Comments": "64e167eb is not responsible, it change the name of an argument\nedec3e1b is not responsible, it's a debug log\nd4cf1156 is not responsible , it change the name of an argument\nb055e168 It's a false positive, \n8c53d87a is not responsible, it's an importation \n8880aadb it's responsible\ne61bf701 it's a false positive because the lines are moved in the fix-commit, it's not responsible.\nc7718b2d is not responsible, it's a debug log."
}
